#ifndef RGC_COMMON_H
#define RGC_COMMON_H

#define RGC_TRIGGER_CMD ("RGC_TRIGGER")
#define RGC_TRIGGER_CMD_SIZE (sizeof(RGC_TRIGGER_CMD)-1)
#define RGC_TRIGGER_DELAY_MS (200U)
#define RGC_RECEIVER_DEFAULT_TIMEOUT_MS (500U)

#endif