#ifndef RGC_COMMON_H
#define RGC_COMMON_H

#define RGC_TRIGGER_CMD ("RGC_TRIGGER")
#define RGC_TRIGGER_CMD_SIZE (sizeof(RGC_TRIGGER_CMD)-1)
#define RGC_TRIGGER_DELAY_MS (1000U)
#define RGC_RECEIVER_DEFAULT_TIMEOUT_MS (500U)
#define RGC_PLATFORM_DEBUG_UART_BAUDRATE (57600)
#define RGC_PLATFORM_RECEIVER_UART_BAUDRATE (2000)

#endif